# Generated by Django 4.2.28 on 2026-02-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('bristol', 'The Wave (Bristol)'), ('cornwall', 'Newquay (Cornwall)'), ('wales', 'Pembrokeshire (Wales)')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='MeetupSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='hello_world.meetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meetup')},
            },
        ),
    ]
