# Generated by Django 4.2.27 on 2026-02-25 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_world', '0003_story_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(choices=[('cornwall-jan', 'Cornwall - January'), ('devon-feb', 'Devon - February'), ('pembrokeshire-mar', 'Pembrokeshire - March'), ('bristol-apr', 'Bristol - April')], max_length=50)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_up_at'],
                'unique_together': {('user', 'trip')},
            },
        ),
    ]
