# Generated by Django 4.2.27 on 2026-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_tripsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsignup',
            name='trip',
            field=models.CharField(choices=[('cornwall-jan', 'Cornwall - January'), ('devon-feb', 'Devon - February'), ('pembrokeshire-mar', 'Pembrokeshire - March'), ('croyde-apr', 'Croyde - April')], max_length=50),
        ),
    ]
