# Generated by Django 4.2.27 on 2026-02-25 13:51

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_alter_tripsignup_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
