# Generated by Django 4.2.27 on 2026-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_alter_comment_content_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(),
        ),
    ]
